echo "AurorOS Makefile"
echo "  make - builds OS"
echo "  make help - shows this help"
echo "  make install-ubuntu - installs required packages for Ubuntu (you need to manually install on other distro)"
echo "  make run - tries to run OS on Ubuntu"